# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host:     huachamacare
  port:     5433
  database: actas
  username: sisdesa
  password: 12qwaszx

production:
  <<: *default
  host:     huachamacare
  port:     5433
  database: actas
  username: sisdesa
  password: 12qwaszx


#development:
#  <<: *default
#  host:     huachamacare
#  port:     5434
#  database: cedulados
#  username: sisdesa
#  password: 12qwaszx

cedulados_development:
  <<: *default
  host:     huachamacare
  port:     5434
  database: cedulados
  username: sisdesa
  password:

cedulados_production:
  <<: *default
  host:     huachamacare
  port:     5434
  database: cedulados
  username: sisdesa
  password:

intranet_development:
  <<: *default
  host:     huachamacare
  port:     5432
  database: intranet
  username: sisdesa
  password: 12qwaszx

intranet_production:
  <<: *default
  host:     huachamacare
  port:     5432
  database: intranet
  username: sisdesa
  password: 12qwaszx



# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
#test:
#  <<: *default
#  database: actas_test


